name: Test

on:
  push:
    paths:
      - .github/**/*
      - ./**/*.c
      - ./**/*.h
      - ./**/mocks/*
  workflow_dispatch:

jobs:
  test-release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@latest
      - name: Setup clang
        shell: bash
        run: |
          apt update
          apt install clang
          clang -v
      - name: Run tests
        shell: bash
        run: |
          make test

  test-debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@latest
      - name: Setup clang
        shell: bash
        run: |
          apt update
          apt install clang
          clang -v
      - name: Run tests
        shell: bash
        run: |
          make test_dbg
