name: Test

on:
  push:
    paths:
      - .github/**/*
      - Makefile
      - **.c
      - **.h
      - tests/**/*.c
      - tests/**/*.h
      - tests/mocks/**/*
      - benchmarks/**/*.c
      - benchmarks/**/*.h
  workflow_dispatch:

jobs:
  test-release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup clang
        shell: bash
        run: |
          sudo apt update
          sudo apt install clang-15
      - shell: bash
        run: |
          gcc -v
          clang-15 -v
      - name: Run tests
        shell: bash
        run: |
          set -ex

          alias clang=clang-15
          make test

  test-debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup clang
        shell: bash
        run: |
          sudo apt update
          sudo apt install clang-15
      - shell: bash
        run: |
          gcc -v
          clang-15 -v
      - name: Run tests
        shell: bash
        run: |
          set -ex

          alias clang=clang-15
          make test_dbg
